# Use iOS 9 and above
platform :ios, '9.0'

# Specify Workspace
workspace 'SDJAvenir'

target 'SDJAvenir' do
  # Stripe
  pod 'Stripe', '~> 11.2.0'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'

  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Functions', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  # pod 'Firebase/Invites', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/RemoteConfig', '~> 5.11.0'
  pod 'Firebase/Storage', '~> 5.11.0'
  pod 'Firebase/Performance', '~> 5.11.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'

  # pod 'RNSound', :path => '../node_modules/react-native-sound'

end